### ISSUE TITLE
request for training data

### ISSUE THREAD

**Issue by ProgrammingElite** [TomJZ/KNODE-Cosserat#1]
Excuse me, how to generate the training data? Could you share the `datas` and `physical_experiment_data` folder?

**Comment by rianadon** [comment]
Thanks for pointing out they were not in the repo! I've uploaded the `physical_experiment_data` folder as well as instructions of how to generate the files under the `datas` folder.

**Comment by ProgrammingElite** [comment]
您的邮件已收到，谢谢！
